### ISSUE TITLE
Provide default styles

### ISSUE THREAD

**Issue by afcapel** [afcapel/stimulus-autocomplete#105]
All the examples use css from bootstrap v4 to styles the results box. While there's little to it, it'd be nicer if we provided a minimal css so the autocomplete is easier to use for folks that don't use bootstrap.

An example using Tailwind would be nice too.

**Comment by brentgreeff** [comment]
If anyone has some basic CSS they can paste here - would be most appreciated.

This project is pretty amazing - very easy to get going, and then you hit the CSS and have to use the inspector to figure it out.

**Comment by brentgreeff** [comment]
Here is some

```scss

[data-controller=autocomplete] {
  margin: 1em;

  .list-group {
    margin: 0;
    padding: 0;
  }

  .list-group-item {
    position: relative;
    display: block;
    padding: 0.75rem 1.25rem;
    margin-bottom: -1px;
    background-color: #fff;
    border: 1px solid rgba(0,0,0,.125);
    width: 30em;

    &:hover {
      z-index: 2;
      color: #fff;
      background-color: #007bff;
      border-color: #007bff;
    }
  }

  .list-group-item.active {
    z-index: 2;
    color: #fff;
    background-color: #007bff;
    border-color: #007bff;
  }

  .list-group-item:first-child {
    border-top-left-radius: 0.25rem;
    border-top-right-radius: 0.25rem;
  }
}
```
